using System.Collections.Generic;

namespace DreamEchoesCore.Utils;

internal class Preload
{
    public static List<(string, string)> Names = [
        ("GG_Traitor_Lord", "Battle Scene"),
        ("RestingGrounds_07", "Dream Moth"),
        ("GG_Radiance", "Boss Control/Absolute Radiance"),
        ("Dream_Backer_Shrine", "dream_BG_plats_0002_2"),
        ("Dream_Backer_Shrine", "_Items"),
        ("Dream_Backer_Shrine", "dream_BG_plats_0001_3"),
        ("Dream_Backer_Shrine", "mines_rocks_06"),
        ("Dream_Backer_Shrine", "dream_large_plat_01 (2)"),
        ("Dream_Backer_Shrine", "back_arches"),
        ("Dream_Backer_Shrine", "_Effects"),
        ("Dream_Backer_Shrine", "water_fog (1)"),
        ("Dream_Backer_Shrine", "dream_catcher_active_01 (3)"),
        // ("Dream_Backer_Shrine", "Roof Collider (2)"),
        ("Dream_Backer_Shrine", "dream_catcher_active_03 (2)"),
        ("Dream_Backer_Shrine", "dream_BG_plats_0002_2 (1)"),
        ("Dream_Backer_Shrine", "_Scenery"),
        ("Dream_Backer_Shrine", "formal_fence (9)"),
        // ("Dream_Backer_Shrine", "Inspect Region"),
        ("Dream_Backer_Shrine", "dream_fog"),
        ("Dream_Backer_Shrine", "dream_grass_3 (6)"),
        ("Dream_Backer_Shrine", "_Enemies"),
        // ("Dream_Backer_Shrine", "Audio Player Actor"),
        ("Dream_Backer_Shrine", "_Managers"),
        ("Dream_Backer_Shrine", "dream_fog (1)"),
        ("Dream_Backer_Shrine", "_Camera Lock Zones"),
        ("Dream_Backer_Shrine", "dream_grass_3 (9)"),
        ("Dream_Backer_Shrine", "dream_catcher_active_02 (1)"),
        ("Dream_Backer_Shrine", "_NPCs"),
        // ("Dream_Backer_Shrine", "dream_grass_1 (12)"),
        ("Dream_Backer_Shrine", "dream_grass_1 (3)"),
        ("Dream_Backer_Shrine", "dream_catcher_active_01 (4)"),
        ("Dream_Backer_Shrine", "_SceneManager"),
        // ("Dream_Backer_Shrine", "dream_plat_small (4)"),
        ("Dream_Backer_Shrine", "formal_fence (2)"),
        // ("Dream_Backer_Shrine", "TileMap"),
        // ("Dream_Backer_Shrine", "door2"),
        ("Dream_Backer_Shrine", "dream_grass_1"),
        ("Dream_Backer_Shrine", "water_fog"),
        // ("Dream_Backer_Shrine", "TileMap Render Data"),
        ("Dream_Backer_Shrine", "dream_grass_1 (11)"),
        // ("Dream_Backer_Shrine", "dream_grass_1 (9)"),
        ("Dream_Backer_Shrine", "formal_fence (4)"),
        ("Dream_Backer_Shrine", "cd_archway_full (2)"),
        ("Dream_Backer_Shrine", "dream_fog (3)"),
        ("Dream_Backer_Shrine", "_Markers"),
        // ("Dream_Backer_Shrine", "door1"),
        ("Dream_Backer_Shrine", "_Transition Gates"),
        // ("Dream_Backer_Shrine", "dream_plat_med (5)"),
        ("Dream_Backer_Shrine", "dreamcatcher_04 (8)"),
        ("Dream_Backer_Shrine", "World Edge (1)"),
        ("Dream_Backer_Shrine", "_Props"),
        // ("Dream_Backer_Shrine", "dream_lamp_01 (3)"),
        ("Dream_Backer_Shrine", "dreamcatcher_04 (5)"),
        // ("Dream_Backer_Shrine", "Shrine_of_Believers_Ext"),
        ("Dream_Backer_Shrine", "dream_scene pieces"),
        ("Dream_Backer_Shrine", "BlurPlane"),
        // ("Dream_Backer_Shrine", "Dream Dialogue"),
        // ("Dream_Backer_Shrine", "moth_ghost_idle0002"),
        ("Dream_Backer_Shrine", "CameraLockArea"),
        ("Dream_Backer_Shrine", "Dream Fall Catcher"),
        ("Dream_Backer_Shrine", "formal_fence (7)"),
        // ("Dream_Backer_Shrine", "dream_particle_03"),
        ("Dream_Backer_Shrine", "formal_fence (5)"),
        // ("Dream_Backer_Shrine", "Roof Collider (1)"),
        // ("Dream_Backer_Shrine", "Particle System glowies"),
        ("Dream_Backer_Shrine", "dream_grass_1 (2)"),
        ("Dream_Backer_Shrine", "World Edge"),
        ("Dream_Backer_Shrine", "dream_mid_plat"),
        ("Dream_Backer_Shrine", "formal_fence (6)"),
        ("Dream_Backer_Shrine", "formal_fence"),
        ("Dream_Backer_Shrine", "dreamcatcher_04 (9)"),
        ("Dream_Backer_Shrine", "Superdash Cancel (2)"),
        // ("Dream_Backer_Shrine", "dream_large_plat_01 (1)"),
        ("Dream_Backer_Shrine", "formal_fence (1)"),
        ("Dream_Backer_Shrine", "_Areas"),
        // ("Dream_Backer_Shrine", "dream_plat_small (3)"),
        ("Dream_Backer_Shrine", "dream_BG_plats_0001_3 (1)"),
        // ("Dream_Backer_Shrine", "dream_lamp_01 (1)"),
        // ("Dream_Backer_Shrine", "dream_grass_1 (13)"),
        // ("Dream_Backer_Shrine", "dream_plat_small (2)"),
        ("Dream_Backer_Shrine", "floor_02 (2)"),
        ("Dream_Backer_Shrine", "dream_large_plat_01"),
        ("Dream_Backer_Shrine", "dream_lamp_01 (2)"),
        ("Dream_Backer_Shrine", "dreamcatcher_04 (10)"),
        // ("Dream_Backer_Shrine", "Shrine_of_Believers_Ext_door"),
        ("Dream_Backer_Shrine", "Dream Entry"),
        ("Dream_Backer_Shrine", "dream_catcher_active_01 (5)"),
        ("Dream_Backer_Shrine", "dream_grass_3 (10)"),
        ("Dream_Backer_Shrine", "cd_archway_full (3)"),
        ("Dream_Backer_Shrine", "dream_grass_1 (10)"),
        ("Dream_Backer_Shrine", "formal_fence (3)"),
        ("Dream_Backer_Shrine", "dreamcatcher_04 (6)"),
        ("Dream_Backer_Shrine", "dream_BG_plats_0000_4"),
        // ("Dream_Backer_Shrine", "dream_plat_small (5)"),
        ("Dream_Backer_Shrine", "Superdash Cancel (1)"),
        // ("Dream_Backer_Shrine", "dream_plat_med (4)"),
        ("Dream_Backer_Shrine", "dream_catcher_active_02"),
        // ("Dream_Backer_Shrine", "dream_grass_1 (8)"),
        // ("Dream_Backer_Shrine", "Roof Collider"),
        ("Mines_34", "mine_summit_statue"),
        ("RestingGrounds_04", "dreamer_statue/Dreamer_statue_horn_left"),
        ("RestingGrounds_04", "dreamer_statue/Dreamer_statue_horn_right"),
        ("Ruins1_06", "ruind_bridge_base_04 (1)"),
        ("Ruins1_06", "ruind_bridge_base_01"),
        ("Ruins1_06", "ruind_bridge_base_04 (3)"),
        ("Ruins1_06", "ruind_bridge_base_arch_07"),
        // ("Ruins1_06", "ruind_bridge_roof_01 (9)"),
        ("Ruins1_06", "ruind_bridge_base_arch_05"),
        ("Ruins1_06", "ruind_bridge_base_arch_10"),
        ("Ruins1_06", "ruind_bridge_base_arch_05 (2)"),
        ("Ruins1_06", "ruind_bridge_base_arch_04 (4)"),
        ("Ruins1_06", "ruind_bridge_base_arch_09"),
        ("Ruins1_06", "ruind_bridge_base_04"),
        // ("Ruins1_06", "ruind_bridge_roof_spike"),
        ("Ruins1_06", "ruind_bridge_base_07"),
        // ("Ruins1_06", "ruind_bridge_roof_spike (6)"),
        ("Ruins1_06", "ruind_bridge_base_arch_03"),
        ("Ruins1_06", "ruind_bridge_base_arch_05 (1)"),
        ("Ruins1_06", "ruind_bridge_base_05"),
        ("Ruins1_06", "ruind_bridge_base_03 (1)"),
        ("Ruins1_06", "ruind_bridge_base_arch_05 (3)"),
        ("Ruins1_06", "ruind_bridge_base_arch_04 (1)"),
        // ("Ruins1_06", "ruind_bridge_roof_spike (1)"),
        ("Ruins1_06", "ruind_bridge_base_03"),
        // ("Ruins1_06", "ruind_bridge_roof_spike (5)"),
        ("Ruins1_06", "ruind_bridge_base_arch_04"),
        ("Ruins1_06", "ruind_bridge_base_06 (2)"),
        ("Ruins1_06", "ruind_bridge_base_08"),
        // ("Ruins1_06", "ruind_bridge_roof_spike (3)"),
        ("Ruins1_06", "ruind_bridge_base_06 (3)"),
        ("Ruins1_06", "ruind_bridge_base_06"),
        // ("Ruins1_06", "ruind_bridge_roof_01 (2)"),
        ("Ruins1_06", "ruind_bridge_base_03 (2)"),
        ("Ruins1_06", "ruind_bridge_base_arch_05 (4)"),
        ("Ruins1_06", "ruind_bridge_base_arch_04 (2)"),
        // ("Ruins1_06", "ruind_bridge_roof_01 (3)"),
        ("Ruins1_06", "ruind_bridge_base_arch_08"),
        // ("Ruins1_06", "ruind_bridge_roof_01 (5)"),
        // ("Ruins1_06", "ruind_bridge_roof_04 (1)"),
        ("Ruins1_06", "ruind_bridge_base_arch_06"),
        ("Ruins1_06", "ruind_bridge_base_10"),
        ("Ruins1_06", "ruind_bridge_base_arch_04 (3)"),
        // ("Ruins1_06", "ruind_bridge_roof_04"),
        ("Ruins1_06", "ruind_bridge_base_06 (1)"),
        // ("Ruins1_06", "ruind_bridge_roof_spike (4)"),
        // ("Ruins1_06", "ruind_bridge_roof_spike (2)"),
        ("Ruins1_06", "ruind_bridge_base_04 (2)"),
        // ("Ruins1_06", "ruind_bridge_roof_01 (8)"),
        // ("Ruins1_06", "ruind_bridge_roof_01 (4)"),
        ("Ruins1_06", "fungd_floor_32"),
        ("Ruins1_06", "fungd_floor_09 (4)"),
        ("Ruins1_06", "fungd_floor_31"),
        ("Ruins1_06", "fungd_floor_22"),
        ("Ruins1_06", "fungd_floor_15"),
        ("Ruins1_06", "fungd_floor_41"),
        ("Ruins1_06", "fungd_floor_05 (2)"),
        ("Ruins1_06", "fungd_floor_17 (1)"),
        ("Ruins1_06", "fungd_floor_30"),
        ("Ruins1_06", "fungd_floor_20"),
        ("Ruins1_06", "fungd_floor_09 (6)"),
        ("Ruins1_06", "fungd_floor_12"),
        ("Ruins1_06", "fungd_floor_22 (1)"),
        ("Ruins1_06", "fungd_floor_14"),
        ("Ruins1_06", "fungd_floor_54"),
        ("Ruins1_06", "fungd_floor_28"),
        ("Ruins1_06", "fungd_floor_21 (1)"),
        ("Ruins1_06", "fungd_floor_23"),
        ("Ruins1_06", "fungd_floor_30 (1)"),
        ("Ruins1_06", "fungd_floor_10 (4)"),
        ("Ruins1_06", "fungd_floor_21"),
        ("Ruins1_06", "fungd_floor_03"),
        ("Ruins1_06", "fungd_floor_38"),
        ("Ruins1_06", "fungd_floor_49"),
        ("Ruins1_06", "fungd_floor_61"),
        ("Ruins1_06", "fungd_floor_25 (1)"),
        ("Ruins1_06", "fungd_floor_26"),
        ("Ruins1_06", "fungd_floor_19 (1)"),
        ("Ruins1_06", "fungd_floor_20 (1)"),
        ("Ruins1_06", "fungd_floor_65"),
        ("Ruins1_06", "fungd_floor_18"),
        ("Ruins1_06", "fungd_floor_19"),
        ("Ruins1_06", "fungd_floor_07"),
        ("Ruins1_06", "fungd_floor_53"),
        ("Ruins1_06", "fungd_floor_29 (1)"),
        ("Ruins1_06", "fungd_floor_10 (3)"),
        ("Ruins1_06", "fungd_floor_05 (4)"),
        ("Ruins1_06", "fungd_floor_47"),
        ("Ruins1_06", "fungd_floor_05 (3)"),
        ("Ruins1_06", "fungd_floor_28 (1)"),
        ("Ruins1_06", "fungd_floor_07 (4)"),
        ("Ruins1_06", "fungd_floor_07 (2)"),
        ("Ruins1_06", "fungd_floor_13"),
        ("Ruins1_06", "fungd_floor_25"),
        ("Ruins1_06", "fungd_floor_09 (2)"),
        ("Ruins1_06", "fungd_floor_48"),
        ("Ruins1_06", "fungd_floor_32 (1)"),
        ("Ruins1_06", "fungd_floor_43"),
        ("Ruins1_06", "fungd_floor_09 (5)"),
        ("Ruins1_06", "fungd_floor_56"),
        ("Ruins1_06", "fungd_floor_64"),
        ("Ruins1_06", "fungd_floor_24 (1)"),
        ("Ruins1_06", "fungd_floor_06 (1)"),
        ("Ruins1_06", "fungd_floor_34 (1)"),
        ("Ruins1_06", "fungd_floor_46"),
        ("Ruins1_06", "fungd_floor_17"),
        ("Ruins1_06", "fungd_floor_26 (1)"),
        ("Ruins1_06", "fungd_floor_55"),
        ("Ruins1_06", "fungd_floor_06 (3)"),
        ("Ruins1_06", "fungd_floor_09 (1)"),
        ("Ruins1_06", "fungd_floor_06 (2)"),
        ("Ruins1_06", "fungd_floor_24"),
        ("Ruins1_06", "fungd_floor_52"),
        ("Ruins1_06", "fungd_floor_06 (4)"),
        ("Ruins1_06", "fungd_floor_05"),
        ("Ruins1_06", "fungd_floor_07 (1)"),
        ("Ruins1_06", "fungd_floor_44"),
        ("Ruins1_06", "fungd_floor_31 (1)"),
        ("Ruins1_06", "fungd_floor_42"),
        ("Ruins1_06", "fungd_floor_16"),
        ("Ruins1_06", "fungd_floor_03 (1)"),
        ("Ruins1_06", "fungd_floor_40"),
        ("Ruins1_06", "fungd_floor_27 (1)"),
        ("Ruins1_06", "fungd_floor_09"),
        ("Ruins1_06", "fungd_floor_34"),
        ("Ruins1_06", "fungd_floor_58"),
        ("Ruins1_06", "fungd_floor_10 (1)"),
        ("Ruins1_06", "fungd_floor_07 (3)"),
        ("Ruins1_06", "fungd_floor_10"),
        ("Ruins1_06", "fungd_floor_62"),
        ("Ruins1_06", "fungd_floor_59"),
        ("Ruins1_06", "fungd_floor_63"),
        ("Ruins1_06", "fungd_floor_45"),
        ("Ruins1_06", "fungd_floor_23 (1)"),
        ("Ruins1_06", "fungd_floor_36"),
        ("Ruins1_06", "fungd_floor_66"),
        ("Ruins1_06", "fungd_floor_27"),
        ("Ruins1_06", "fungd_floor_50"),
        ("Ruins1_06", "fungd_floor_51"),
        ("Ruins1_06", "fungd_floor_33 (1)"),
        ("Ruins1_06", "fungd_floor_18 (1)"),
        ("Ruins1_06", "fungd_floor_11"),
        ("Ruins1_06", "tile_floor"),
        ("Ruins1_06", "fungd_floor_06"),
        ("Ruins1_06", "fungd_floor_09 (3)"),
        ("Ruins1_06", "fungd_floor_33"),
        ("Ruins1_06", "fungd_floor_60"),
        ("Ruins1_06", "fungd_floor_37"),
        ("Ruins1_06", "fungd_floor_57"),
        ("Ruins1_06", "fungd_floor_05 (1)"),
        ("Ruins1_06", "fungd_floor_29"),
        ("Ruins1_06", "fungd_floor_35"),
        ("Ruins1_06", "fungd_floor_10 (5)"),
        ("Ruins1_06", "fungd_floor_10 (2)"),
        ("Ruins1_06", "fungd_floor_39"),
        ("Ruins1_27", "_Scenery")
    ];
}
