using System.Collections.Generic;

namespace DreamEchoesCore.Misc;

internal class Preload
{
    public static List<(string, string)> Names = [
        ("RestingGrounds_07", "Dream Moth"),
        ("GG_Radiance", "Boss Control/Absolute Radiance"),
        ("Dream_Backer_Shrine", "dream_BG_plats_0002_2"),
        ("Dream_Backer_Shrine", "_Items"),
        ("Dream_Backer_Shrine", "dream_BG_plats_0001_3"),
        ("Dream_Backer_Shrine", "mines_rocks_06"),
        ("Dream_Backer_Shrine", "dream_large_plat_01 (2)"),
        ("Dream_Backer_Shrine", "back_arches"),
        ("Dream_Backer_Shrine", "_Effects"),
        ("Dream_Backer_Shrine", "water_fog (1)"),
        ("Dream_Backer_Shrine", "dream_catcher_active_01 (3)"),
        ("Dream_Backer_Shrine", "Roof Collider (2)"),
        ("Dream_Backer_Shrine", "dream_catcher_active_03 (2)"),
        ("Dream_Backer_Shrine", "dream_BG_plats_0002_2 (1)"),
        ("Dream_Backer_Shrine", "_Scenery"),
        ("Dream_Backer_Shrine", "formal_fence (9)"),
        // ("Dream_Backer_Shrine", "Inspect Region"),
        ("Dream_Backer_Shrine", "dream_fog"),
        ("Dream_Backer_Shrine", "dream_grass_3 (6)"),
        ("Dream_Backer_Shrine", "_Enemies"),
        ("Dream_Backer_Shrine", "Audio Player Actor"),
        ("Dream_Backer_Shrine", "_Managers"),
        ("Dream_Backer_Shrine", "dream_fog (1)"),
        ("Dream_Backer_Shrine", "_Camera Lock Zones"),
        ("Dream_Backer_Shrine", "dream_grass_3 (9)"),
        ("Dream_Backer_Shrine", "dream_catcher_active_02 (1)"),
        ("Dream_Backer_Shrine", "_NPCs"),
        ("Dream_Backer_Shrine", "dream_grass_1 (12)"),
        ("Dream_Backer_Shrine", "dream_grass_1 (3)"),
        ("Dream_Backer_Shrine", "dream_catcher_active_01 (4)"),
        ("Dream_Backer_Shrine", "_SceneManager"),
        ("Dream_Backer_Shrine", "dream_plat_small (4)"),
        ("Dream_Backer_Shrine", "formal_fence (2)"),
        ("Dream_Backer_Shrine", "TileMap"),
        // ("Dream_Backer_Shrine", "door2"),
        ("Dream_Backer_Shrine", "dream_grass_1"),
        ("Dream_Backer_Shrine", "water_fog"),
        ("Dream_Backer_Shrine", "TileMap Render Data"),
        ("Dream_Backer_Shrine", "dream_grass_1 (11)"),
        ("Dream_Backer_Shrine", "dream_grass_1 (9)"),
        ("Dream_Backer_Shrine", "formal_fence (4)"),
        ("Dream_Backer_Shrine", "cd_archway_full (2)"),
        ("Dream_Backer_Shrine", "dream_fog (3)"),
        ("Dream_Backer_Shrine", "_Markers"),
        // ("Dream_Backer_Shrine", "door1"),
        ("Dream_Backer_Shrine", "_Transition Gates"),
        ("Dream_Backer_Shrine", "dream_plat_med (5)"),
        ("Dream_Backer_Shrine", "dreamcatcher_04 (8)"),
        ("Dream_Backer_Shrine", "World Edge (1)"),
        ("Dream_Backer_Shrine", "_Props"),
        ("Dream_Backer_Shrine", "dream_lamp_01 (3)"),
        ("Dream_Backer_Shrine", "dreamcatcher_04 (5)"),
        // ("Dream_Backer_Shrine", "Shrine_of_Believers_Ext"),
        ("Dream_Backer_Shrine", "dream_scene pieces"),
        ("Dream_Backer_Shrine", "BlurPlane"),
        // ("Dream_Backer_Shrine", "Dream Dialogue"),
        // ("Dream_Backer_Shrine", "moth_ghost_idle0002"),
        ("Dream_Backer_Shrine", "CameraLockArea"),
        ("Dream_Backer_Shrine", "Dream Fall Catcher"),
        ("Dream_Backer_Shrine", "formal_fence (7)"),
        // ("Dream_Backer_Shrine", "dream_particle_03"),
        ("Dream_Backer_Shrine", "formal_fence (5)"),
        ("Dream_Backer_Shrine", "Roof Collider (1)"),
        // ("Dream_Backer_Shrine", "Particle System glowies"),
        ("Dream_Backer_Shrine", "dream_grass_1 (2)"),
        ("Dream_Backer_Shrine", "World Edge"),
        ("Dream_Backer_Shrine", "dream_mid_plat"),
        ("Dream_Backer_Shrine", "formal_fence (6)"),
        ("Dream_Backer_Shrine", "formal_fence"),
        ("Dream_Backer_Shrine", "dreamcatcher_04 (9)"),
        ("Dream_Backer_Shrine", "Superdash Cancel (2)"),
        ("Dream_Backer_Shrine", "dream_large_plat_01 (1)"),
        ("Dream_Backer_Shrine", "formal_fence (1)"),
        ("Dream_Backer_Shrine", "_Areas"),
        ("Dream_Backer_Shrine", "dream_plat_small (3)"),
        ("Dream_Backer_Shrine", "dream_BG_plats_0001_3 (1)"),
        ("Dream_Backer_Shrine", "dream_lamp_01 (1)"),
        ("Dream_Backer_Shrine", "dream_grass_1 (13)"),
        ("Dream_Backer_Shrine", "dream_plat_small (2)"),
        ("Dream_Backer_Shrine", "floor_02 (2)"),
        ("Dream_Backer_Shrine", "dream_large_plat_01"),
        ("Dream_Backer_Shrine", "dream_lamp_01 (2)"),
        ("Dream_Backer_Shrine", "dreamcatcher_04 (10)"),
        // ("Dream_Backer_Shrine", "Shrine_of_Believers_Ext_door"),
        ("Dream_Backer_Shrine", "Dream Entry"),
        ("Dream_Backer_Shrine", "dream_catcher_active_01 (5)"),
        ("Dream_Backer_Shrine", "dream_grass_3 (10)"),
        ("Dream_Backer_Shrine", "cd_archway_full (3)"),
        ("Dream_Backer_Shrine", "dream_grass_1 (10)"),
        ("Dream_Backer_Shrine", "formal_fence (3)"),
        ("Dream_Backer_Shrine", "dreamcatcher_04 (6)"),
        ("Dream_Backer_Shrine", "dream_BG_plats_0000_4"),
        ("Dream_Backer_Shrine", "dream_plat_small (5)"),
        ("Dream_Backer_Shrine", "Superdash Cancel (1)"),
        ("Dream_Backer_Shrine", "dream_plat_med (4)"),
        ("Dream_Backer_Shrine", "dream_catcher_active_02"),
        ("Dream_Backer_Shrine", "dream_grass_1 (8)"),
        ("Dream_Backer_Shrine", "Roof Collider"),
        ("Mines_34", "mine_summit_statue"),
    ];
}
